layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: haochuanwei
  # instagram: your_username
  # keybase: your_username
  linkedin: haochuan-wei
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: ErnieThornhill
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: ErnieThornhill
    web_url: https://github.com/ErnieThornhill
  - name: Natural Language Processing
  - name: Quantum Computing with Q#
    web_url: https://github.com/haochuanwei/learn_quantum_computing
